import type { Metadata } from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import Header from "@/components/header";


const inter = Inter({
  subsets: ["latin"],

})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} max-h-screen   antialiased bg-gradient-to-br from-linear1 to-linear2 `}
      >
        <div className="grid grid-cols-1 md:grid-cols-4 md:my-8">
          <div className="col-span-1">
            <Sidebar/>
          </div>
          <div className="col-span-3 mx-1 mt-[11px]">
            <Header/>
          {children}
          </div>
        </div>
      </body>
    </html>
  );
}
